[package]
authors = ["Age Manning <Age@AgeManning.com>"]
edition = "2018"
name = "enr"
version = "0.1.0-alpha-1"
description = "Rust implementation of Ethereum Node Record (ENR) EIP778"
readme = "./README.md"
keywords = ["ethereum", "ENR", "Record", "EIP778", "Node"]
repository = "https://github.com/AgeManning/enr"
categories = ["cryptography::cryptocurrencies"]
license = "MIT"
exclude = [
	".gitignore",
	".github/*"
]

[[bin]]
name = "enr-cli"
path = "src/enr-cli.rs"

[dependencies]
base64 = "0.10.1"
bs58 = "0.3.0"
clap = "2.33.0"
ed25519-dalek = "1.0.0-pre.3"
hex = "0.4.0"
libsecp256k1 = "0.3.1"
log = "0.4.8"
rand = "0.7.2"
rlp = "0.4.3"
sha3 = "0.8.2"
libp2p-core = { version = "0.16.0", optional = true }

[dependencies.serde]
optional = true
version = "1.0.93"

[features]
libp2p = ["libp2p-core"]

[lib]
name = "enr"
path = "src/lib.rs"

