[package]
authors = ["Age Manning <Age@AgeManning.com>"]
edition = "2018"
name = "enr"
version = "0.1.0-alpha.3"
description = "Rust implementation of Ethereum Node Record (ENR) EIP778"
readme = "./README.md"
keywords = ["ethereum", "enr", "record", "EIP778", "node"]
repository = "https://github.com/AgeManning/enr"
categories = ["cryptography::cryptocurrencies"]
license = "MIT"
exclude = [
	".gitignore",
	".github/*"
]

[dependencies]
base64 = "0.12.0"
bs58 = "0.3.0"
hex = "0.4.2"
log = "0.4.8"
rand = "0.7.3"
rlp = "0.4.4"
sha3 = "0.8.2"
zeroize = "1.1.0"
libsecp256k1 = { version = "^0", optional = true }
serde = { version = "1.0.104", optional = true }
libp2p-core = { version = "^0", optional = true }
ed25519-dalek = { version = "1.0.0-pre.3", optional = true }

[features]
default = ["serde", "libsecp256k1" ]
libp2p = ["libp2p-core"]
ed25519 = ["ed25519-dalek"]

[lib]
name = "enr"
path = "src/lib.rs"

[package.metadata.docs.rs]
all-features = true
